# Generated by Django 5.1.3 on 2024-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_factura', models.PositiveIntegerField()),
                ('id_cliente', models.CharField(max_length=30, verbose_name='Id del cliente')),
                ('id_producto', models.CharField(max_length=30, verbose_name='Id del producto')),
                ('metodo_pago', models.CharField(max_length=30, verbose_name='Método de pago')),
                ('total', models.PositiveIntegerField(verbose_name='Total')),
                ('id_trabajador', models.CharField(max_length=30, verbose_name='Id del trabajador')),
                ('fecha', models.DateField(verbose_name='fecha de realización')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
            },
        ),
    ]
