# Generated by Django 5.1.3 on 2024-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.PositiveIntegerField()),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('precio', models.PositiveIntegerField(verbose_name='Precio del producto')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock del producto')),
                ('categoria', models.CharField(choices=[('Traje de baño', 'Traje de baño'), ('Accesorios', 'Accesorios'), ('Lenceria', 'Lenceria')], default='Traje de baño', max_length=300, verbose_name='Categoría del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción del producto')),
                ('fecha', models.DateField(verbose_name='fecha de publicación')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
