# Generated by Django 5.1.3 on 2024-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proveedor', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del proveedor')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección del proveedor')),
                ('tipo_prod', models.CharField(max_length=50, verbose_name='Tipo de producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad del producto')),
                ('contacto', models.CharField(max_length=15, verbose_name='Contacto')),
                ('fecha', models.DateField(verbose_name='fecha de entrega')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
