# Generated by Django 5.1.3 on 2024-11-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_trabajador', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del trabajador')),
                ('apellido', models.CharField(max_length=30, verbose_name='apellido del trabajador')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono del trabajador')),
                ('gmail', models.EmailField(max_length=50, verbose_name='Email del trabajador')),
                ('curp', models.CharField(max_length=40, verbose_name='Curp del trabajador')),
                ('rfc', models.CharField(max_length=30, verbose_name='RFC del trabajador')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
    ]
