# Generated by Django 5.1.2 on 2024-11-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.PositiveIntegerField()),
                ('producto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('tipo', models.PositiveIntegerField(verbose_name='Tipo del producto')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad del producto')),
                ('categoria', models.CharField(max_length=300, verbose_name='Categoría del producto')),
                ('id_producto', models.CharField(max_length=30, verbose_name='id del producto')),
                ('disponible', models.CharField(max_length=30, verbose_name='Disponible')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
            },
        ),
    ]
